kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
    - secrets
    providers:
    - aesgcm:
        keys:
        - name: key1
          secret: 7UeIkfo16qCDf+EPovyiARe1C419xwP/q8CtSmf6WDk=
